#!/usr/bin/env bash
#
# Install Photo Dupe on Ubuntu 24.04 (and other Debian-based systems).
#
# Everything goes into your home directory -- no system Python packages are
# touched. Uninstall with ./uninstall.sh.
#
set -euo pipefail

APP_ID="photo-dupe"
PREFIX="${HOME}/.local"
APP_HOME="${PREFIX}/share/${APP_ID}"
VENV="${APP_HOME}/venv"
BIN="${PREFIX}/bin"
SOURCE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

WITH_HEIC=0
SKIP_APT=0

usage() {
    cat <<'USAGE'
Usage: ./install.sh [options]

  --with-heic   also install HEIC/HEIF support (iPhone photos)
  --skip-apt    do not install system packages with apt (use if you have
                already installed the Qt runtime libraries yourself)
  -h, --help    show this message
USAGE
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --with-heic) WITH_HEIC=1 ;;
        --skip-apt)  SKIP_APT=1 ;;
        -h|--help)   usage; exit 0 ;;
        *) echo "Unknown option: $1" >&2; usage; exit 2 ;;
    esac
    shift
done

say()  { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m!!\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31mxx\033[0m %s\n' "$*" >&2; exit 1; }

# --------------------------------------------------------------------------
# 1. Python
# --------------------------------------------------------------------------
command -v python3 >/dev/null 2>&1 || die "python3 was not found."

PY_OK=$(python3 - <<'PY'
import sys
print("yes" if sys.version_info >= (3, 10) else "no")
PY
)
[[ "${PY_OK}" == "yes" ]] || die "Python 3.10 or newer is required (found $(python3 -V))."
say "Using $(python3 -V)"

# --------------------------------------------------------------------------
# 2. System libraries Qt needs
# --------------------------------------------------------------------------
# Qt links these at runtime; without them the app fails to start with an
# error about libEGL.so.1 rather than anything helpful.
APT_PACKAGES=(
    python3-venv python3-pip
    libegl1 libgl1 libglib2.0-0
    libxkbcommon0 libxkbcommon-x11-0
    libxcb-cursor0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1
    libxcb-randr0 libxcb-render-util0 libxcb-shape0 libxcb-xinerama0 libxcb-xkb1
    libdbus-1-3 libfontconfig1 libfreetype6
    libxrandr2 libxi6 libxtst6
)

if [[ "${SKIP_APT}" -eq 0 ]]; then
    if command -v apt-get >/dev/null 2>&1; then
        MISSING=()
        for package in "${APT_PACKAGES[@]}"; do
            if ! dpkg -s "${package}" >/dev/null 2>&1; then
                MISSING+=("${package}")
            fi
        done
        if [[ ${#MISSING[@]} -gt 0 ]]; then
            say "Installing ${#MISSING[@]} system packages (sudo password may be required)"
            printf '    %s\n' "${MISSING[*]}"
            sudo apt-get update -qq
            sudo apt-get install -y "${MISSING[@]}"
        else
            say "System libraries already present"
        fi
    else
        warn "apt-get not found; skipping system packages. Install the Qt6 runtime yourself."
    fi
else
    say "Skipping system packages as requested"
fi

# --------------------------------------------------------------------------
# 3. Virtual environment
# --------------------------------------------------------------------------
say "Creating the application environment in ${VENV}"
mkdir -p "${APP_HOME}"
if [[ ! -x "${VENV}/bin/python" ]]; then
    python3 -m venv "${VENV}" || die "Could not create a virtual environment. Try: sudo apt install python3-venv"
fi
"${VENV}/bin/python" -m pip install --quiet --upgrade pip wheel

say "Installing Photo Dupe and its dependencies"
"${VENV}/bin/python" -m pip install --quiet "${SOURCE_DIR}"
if [[ "${WITH_HEIC}" -eq 1 ]]; then
    say "Adding HEIC/HEIF support"
    "${VENV}/bin/python" -m pip install --quiet "pillow-heif>=0.15"
fi

# --------------------------------------------------------------------------
# 4. Launcher
# --------------------------------------------------------------------------
mkdir -p "${BIN}"
cat > "${BIN}/${APP_ID}" <<LAUNCHER
#!/usr/bin/env bash
# Generated by the Photo Dupe installer.
exec "${VENV}/bin/photo-dupe" "\$@"
LAUNCHER
chmod +x "${BIN}/${APP_ID}"
say "Installed launcher at ${BIN}/${APP_ID}"

# --------------------------------------------------------------------------
# 5. Desktop entry and icon
# --------------------------------------------------------------------------
DESKTOP_DIR="${PREFIX}/share/applications"
ICON_DIR="${PREFIX}/share/icons/hicolor/scalable/apps"
mkdir -p "${DESKTOP_DIR}" "${ICON_DIR}"
install -m 644 "${SOURCE_DIR}/packaging/${APP_ID}.svg" "${ICON_DIR}/${APP_ID}.svg"
sed "s|^Exec=.*|Exec=${BIN}/${APP_ID} gui|" \
    "${SOURCE_DIR}/packaging/${APP_ID}.desktop" > "${DESKTOP_DIR}/${APP_ID}.desktop"
chmod 644 "${DESKTOP_DIR}/${APP_ID}.desktop"

command -v update-desktop-database >/dev/null 2>&1 && \
    update-desktop-database "${DESKTOP_DIR}" >/dev/null 2>&1 || true
command -v gtk-update-icon-cache >/dev/null 2>&1 && \
    gtk-update-icon-cache -f -t "${PREFIX}/share/icons/hicolor" >/dev/null 2>&1 || true
say "Added Photo Dupe to your application menu"

# --------------------------------------------------------------------------
# 6. Check it works, and check PATH
# --------------------------------------------------------------------------
if ! "${VENV}/bin/photo-dupe" --version >/dev/null 2>&1; then
    die "The install finished but 'photo-dupe --version' failed. Run it by hand to see why."
fi

echo
say "Photo Dupe $(${VENV}/bin/photo-dupe --version | awk '{print $NF}') is installed."
echo
if [[ ":${PATH}:" != *":${BIN}:"* ]]; then
    warn "${BIN} is not on your PATH."
    echo "    Add it with:"
    echo "      echo 'export PATH=\"\$HOME/.local/bin:\$PATH\"' >> ~/.bashrc && source ~/.bashrc"
    echo
fi
cat <<NEXT
  Open the app :  photo-dupe          (or find "Photo Dupe" in your menu)
  Scan a folder:  photo-dupe scan ~/Pictures --remember
  Find copies  :  photo-dupe dupes
  Remove it    :  ./uninstall.sh

NEXT
